spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: user
    password: pass
  data:
    mongodb:
      uri: mongodb://mongo:27017/userdb
  jpa:
    hibernate:
      ddl-auto: update   # auto-create tables (good for dev)
    properties:
      hibernate.format_sql: true
server:
  port: 80         # match your container’s port (you currently expose 80)
  servlet:
    context-path: /  # optional, but avoids surprises

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never   # or when_authorized