spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: userdb
    password: userdb
  data:
    mongodb:
      uri: mongodb://mongo:27017/userdb
  jpa:
    hibernate:
      ddl-auto: update   # auto-create tables (good for dev)
    properties:
      hibernate.format_sql: true
server:
  port: 8080